Project initialization
atlascope/atlascope-legacy pull request #1
Opened 2021-11-01 16:32 UTC by mcovalt

This PR brings in the [Girder vue-project-template](https://github.com/girder/vue-project-template).

2021-11-16 19:30 UTC, naglepuff requested changes
Just a quick question about the CI config.

2021-11-16 19:30 UTC, naglepuff commented on .github/workflows/main.yml
> +      - master
Should these be `main`?

2021-11-17 01:08 UTC, mcovalt commented on .github/workflows/main.yml
> +      - master
Nice catch. Thanks!

2021-11-29 18:10 UTC, mcovalt commented on .github/workflows/main.yml
> +      - master
Resolved in 904e500a41aa1bdee02549b5ef42a38a0dc83066.

2021-11-29 18:15 UTC, naglepuff approved these changes

2021-11-30 15:56 UTC, merged